---
functional:
  - Пользователь должен иметь возможность соревноваться с другим пользователем
  - Пользователи должены иметь возможность видеть написание кодов друг у друга
  - Необходимо создать систему рейтингов для пользователей
  - Пользователь должен иметь возможность видеть свой ранг
  - Пользователь должен иметь возможность видеть свой рейтинг
  - Пользователь должен иметь возможность играть с ботом
  - У пользователя должна быть возможность играть с другом по ссылке
  - Пользователь должен иметь возможность зарегестрироваться на сайте
  - Пользователь должен иметь возможность добавить аватарку в свой профиль
  - Пользователь должен иметь возможность указать свой никнейм
  - У пользователя должна быть возможность общаться с помощью чата в лобби
  - Пользоватетели должны иметь возможность общаться друг с другом с помощью чата во время соревенования
  - У пользователя должна быть возможность писать в игре код на языке С++
  - У пользователя должна быть возможность писать в игре код на языке JavaScript
  - У пользователя должна быть возможность писать в игре код на языке С#
  - У пользователя должна быть возможность писать в игре код на языке Rudy
  - У пользователя должна быть возможность писать в игре код на языке Python
  - У пользователя должна быть возможность писать в игре код на языке Kotlin
  - У пользователя должна быть возможность писать в игре код на языке Dart
  - У пользователя должна быть возможность писать в игре код на языке Elixir
  - У пользователя должна быть возможность писать в игре код на языке Php
  - У пользователя должна быть возможность писать в игре код на языке Java
  - У пользователя должна быть возможность писать в игре код на языке Clojure
  - У пользователя должна быть возможность писать в игре код на языке TypeScript
  - Пользователь должен иметь доступ к редактору Vim во время написания написания кода
  - Пользователь должен иметь возможность просматривать завершенные игры
  - На главной странице должен быть топ лист играков
non-functional:
  - Сайт должен быть иметь мобильную версию
  - Сайт должен одновременно обрабатывать минимум 5000 пользователей
  - Сайт должен быть оптимизирован для работы в разных браузерах
  - Интерфейс сайта должен быть удобен и интуитивно понятен пользователям
  - Сайт должен иметь надежную защиту данных пользователей
implicit:
  - Пользователь не должен иметь доступа к профилям других пользователей
  - Пользователь не может менять название сайта
